In [41]:
using LinearAlgebra
using Test

import Base.*, Base.\

In [2]:
struct PasovnaMatrika{T} <: AbstractArray{T, 2}
    pasovi::Dict{Int, Vector{T}} # 0 diagonala, 1, 2, 3...nad diagonalo, -1, -2, ... pod diagonalo
    n::Int
    # function PasovnaMatrika{T}(pasovi::Dict{Int, Vector{T}}, n::Int) where T
    #     new(pasovi, n)
    # end
end

struct ZgornjePasovnaMatrika{T} <: AbstractArray{T, 2}
    pasovi::Dict{Int, Vector{T}} # 0 diagonala, 1, 2, 3...nad diagonalo, -1, -2, ... pod diagonalo
    n::Int
end

struct SpodnjePasovnaMatrika{T} <: AbstractArray{T, 2}
    pasovi::Dict{Int, Vector{T}} # 0 diagonala, 1, 2, 3...nad diagonalo, -1, -2, ... pod diagonalo
    n::Int
end

In [8]:
function Base.size(M::PasovnaMatrika)
    return (M.n, M.n)
end

function Base.size(M::ZgornjePasovnaMatrika)
    return (M.n, M.n)
end

function Base.size(M::SpodnjePasovnaMatrika)
    return (M.n, M.n)
end

In [10]:
function Base.getindex(M::PasovnaMatrika, I::Vararg{Int, 2})
    pas = I[2] - I[1]
    if haskey(M.pasovi, pas)
        if pas >= 0
            return M.pasovi[pas][I[1]]
        else 
            return M.pasovi[pas][I[2]]
        end
    else
        return 0
    end
end

function Base.getindex(M::ZgornjePasovnaMatrika, I::Vararg{Int, 2})
    pas = I[2] - I[1] # should be positive
    if haskey(M.pasovi, pas)
        return M.pasovi[pas][I[1]]
    else
        return 0
    end
end

function Base.getindex(M::SpodnjePasovnaMatrika, I::Vararg{Int, 2})
    pas = I[2] - I[1] # sould be negaive
    if haskey(M.pasovi, pas)
        return M.pasovi[pas][I[2]]
    else
        return 0
    end
end

In [22]:
function Base.setindex!(M::PasovnaMatrika, v, I::Vararg{Int, 2})
    pas = I[2] - I[1]
    if haskey(M.pasovi, pas)
        if pas >= 0
            M.pasovi[pas][I[1]] = v
        else 
            M.pasovi[pas][I[2]] = v
        end
    else
        return error("Vrednosti se lahko nastavi samo v neničelnih pasovih") # dodaj cel pas naenkrat? -> setindex!(A, X, I...)
    end
end

function Base.setindex!(M::SpodnjePasovnaMatrika, v, I::Vararg{Int, 2})
    pas = I[2] - I[1]
    if haskey(M.pasovi, pas)
        M.pasovi[pas][I[2]] = v
    else
        return error("Vrednosti se lahko nastavi samo v neničelnih pasovih") 
    end
end

function Base.setindex!(M::ZgornjePasovnaMatrika, v, I::Vararg{Int, 2})
    pas = I[2] - I[1]
    if haskey(M.pasovi, pas)
        M.pasovi[pas][I[1]] = v
    else
        return error("Vrednosti se lahko nastavi samo v neničelnih pasovih") 
    end
end

In [57]:
function *(M::PasovnaMatrika, v::Vector)
    y = zeros(length(v))
    for (k, pas) in M.pasovi
        for i=1:length(pas)
            row = k<=0 ? -k+i : i # indeks elemneta v pasu
            col = k<=0 ? i : k+i # indeks elemnta v pasu
            y[row] += v[col] * pas[i]
        end
    end
    return y
end

function *(M::ZgornjePasovnaMatrika, v::Vector)
    y = zeros(length(v))
    for (k, pas) in M.pasovi
        for i=1:length(pas)
            row = i # indeks elemneta v pasu
            col = k+i # indeks elemnta v pasu
            y[row] += v[col] * pas[i]
        end
    end
    return y
end

function *(M::SpodnjePasovnaMatrika, v::Vector)
    y = zeros(length(v))
    for (k, pas) in M.pasovi
        for i=1:length(pas)
            row = -k+i # indeks elemneta v pasu
            col = i # indeks elemnta v pasu
            y[row] += v[col] * pas[i]
        end
    end
    return y
end

* (generic function with 367 methods)

In [197]:
function \(M_in::PasovnaMatrika, b::Vector)
    bc = deepcopy(b)
    M = deepcopy(M_in)
    z_pas = maximum(M.pasovi.keys)
    l_pas = minimum(M.pasovi.keys)

    for j=1:M.n
        for i=j+1:min(M.n, -l_pas+j)
            l = M[i, j] / M[j, j]
            M[i, j] = 0
            for k=j+1:min(z_pas+j+1, M.n)
                M[i, k] -= l * M[j, k]
            end
            bc[i] -= bc[j] * l 
        end
    end

    x = zeros(M.n)
    for i=M.n:-1:1
        curr = bc[i] 
        for ii=M.n:-1:i
            curr -= M[i, ii] * x[ii]
        end
        x[i] = curr / M[i, i]
    end
    return x
end


function \(M::SpodnjePasovnaMatrika, b::Vector)

    x = zeros(M.n)
    for i=1:M.n
        curr = b[i] 
        for ii=1:(i-1)
            curr -= M[i, ii] * x[ii]
        end
        x[i] = curr / M[i, i]
    end
    return x
end


function \(M::ZgornjePasovnaMatrika, b::Vector)

    x = zeros(M.n)
    for i=M.n:-1:1
        curr = b[i] 
        for ii=M.n:-1:i
            curr -= M[i, ii] * x[ii]
        end
        x[i] = curr/ M[i, i]
    end
    return x
end

\ (generic function with 138 methods)

In [199]:
@testset "pasovna" begin
    eps = 1e-6

    M = [1 8 11 0; 5 2 9 12; 0 6 3 10; 0 0 7 4]
    P = PasovnaMatrika(Dict([(0, [1, 2, 3, 4]), (-1, [5, 6, 7]), (1, [8, 9, 10]), (2, [11, 12])]), 4)
    for i=1:4, j=1:4
        @test P[i, j] == M[i, j] # test get index?
    end
    @test size(P) == size(M) # test size

    for a = [1, 2], b = [1, 3]
        val = a+b
        P[a, b] = val
        @test P[a, b] == val
    end

    # *
    P = PasovnaMatrika(Dict([(0, [1, 2, 3, 4]), (-1, [5, 6, 7]), (1, [8, 9, 10]), (2, [11, 12])]), 4)
    v = [1, 2, 3, 4]
    @test norm(P*v - M*v) < eps

    P = PasovnaMatrika(Dict([(0, [1.0, 2, 3, 4]), (-1, [5.0, 6, 7]), (1, [8.0, 9, 10]), (2, [11.0, 12])]), 4) # float
    v = [1, 2, 3, 4.0]
    x = P\v
    @test norm(P*x - v) < eps

end

@testset "zgornje-pasovna" begin
    eps = 1e-6

    M = [1 8 11 0; 0 2 9 12; 0 0 3 10; 0 0 0 4]
    P = ZgornjePasovnaMatrika(Dict([(0, [1, 2, 3, 4]), (1, [8, 9, 10]), (2, [11, 12])]), 4)
    for i=1:4, j=1:4
        @test P[i, j] == M[i, j] # test get index?
    end
    @test size(P) == size(M) # test size

    for a = [1, 2], b = [2, 3]
        val = a+b
        P[a, b] = val
        @test P[a, b] == val
    end

    P = ZgornjePasovnaMatrika(Dict([(0, [1, 2, 3, 4]), (1, [8, 9, 10]), (2, [11, 12])]), 4)
    v = [1, 2, 3, 4]
    @test norm(P*v - M*v) < eps

    P = ZgornjePasovnaMatrika(Dict([(0, [1.0, 2, 3, 4]), (1, [8.0, 9, 10]), (2, [11.0, 12])]), 4)
    v = [1, 2, 3, 4.0]
    x = P\v
    @test norm(P*x - v) < eps
end

@testset "spodnje-pasovna" begin
    eps = 1e-6

    M = [1 0 0 0; 5 2 0 0; 11 6 3 0; 0 12 7 4]
    P = SpodnjePasovnaMatrika(Dict([(0, [1, 2, 3, 4]), (-1, [5, 6, 7]), (-2, [11, 12])]), 4)
    for i=1:4, j=1:4
        @test P[i, j] == M[i, j] # test get index?
    end
    @test size(P) == size(M) # test size

    for a = [3, 4], b = [2, 3]
        val = a+b
        P[a, b] = val
        @test P[a, b] == val
    end

    P = SpodnjePasovnaMatrika(Dict([(0, [1, 2, 3, 4]), (-1, [5, 6, 7]), (-2, [11, 12])]), 4)
    v = [1, 2, 3, 4]
    @test norm(P*v - M*v) < eps

    P = SpodnjePasovnaMatrika(Dict([(0, [1.0, 2, 3, 4]), (-1, [5.0, 6, 7]), (-2, [11.0, 12])]), 4)
    v = [1, 2, 3, 4.0]
    x = P\v
    @test norm(P*x - v) < eps
end


Test Summary: | Pass  Total
pasovna       |   23     23
Test Summary:   | Pass  Total
zgornje-pasovna |   23     23
Test Summary:   | Pass  Total
spodnje-pasovna |   23     23


Test.DefaultTestSet("spodnje-pasovna", Any[], 23, false, false)

In [324]:
import LinearAlgebra.lu

function lu(M::PasovnaMatrika)
    # eliminacija  če je zg/sp trikotna ni treba tega

    # for (k, pas) in M.pasovi
    L = Matrix{Float64}(I,M.n, M.n)
    l_pas = minimum(M.pasovi.keys)
    z_pas = maximum(M.pasovi.keys)
    print(l_pas, "bbb", z_pas, "\n")
    A = deepcopy(M)
    
    for j=1:M.n
        for i=j+1:-l_pas+1
            # pas = M.pasovi[k] # najbolj spodnji pas
            l = A[i, j] / A[j,j]
            L[i, j] = l

            for k=j+1:min(z_pas+j+1, M.n)
                if A[j,j] < A[j,k]
                    error("Ni diagonalno dominanbsata")
                end
                print(i, " ", k, "\n")
                A[i, k] = A[i, k] - l * A[j, k]
            end
        end
    end 

    #   ŠE U ZGORNJE/SPODNJE TRIKOTNO PRETVORI
    print(A, "\n")
    display(L)

    for i=1:M.n 
        for j=1:M.n 
            if i>j
                A[i, j] = 0
            end
        end
    end

    return (L, A)

end


lu (generic function with 12 methods)

In [325]:
P = PasovnaMatrika(Dict([(0,[10.0, 15.0, 9.0]), (-1,[4.0, 8.0]), (1, [2.0, 6.0]), (-2, [7.0])]), 3)
display(P)
L, U = lu(P)

3×3 PasovnaMatrika{Float64}:
 10.0   2.0  0
  4.0  15.0  6.0
  7.0   8.0  9.0

3×3 Matrix{Float64}:
 1.0  0.0       0.0
 0.4  1.0       0.0
 0.7  0.464789  1.0

-2bbb140525160028896
2 2
2 3
3 2
3 3
3 3
[10.0 2.0 0; 4.0 14.2 6.0; 7.0 6.6 6.211267605633803]


([1.0 0.0 0.0; 0.4 1.0 0.0; 0.7 0.4647887323943662 1.0], [10.0 2.0 0; 0.0 14.2 6.0; 0.0 0.0 6.211267605633803])

In [326]:
L*U

3×3 Matrix{Float64}:
 10.0   2.0  0.0
  4.0  15.0  6.0
  7.0   8.0  9.0

In [307]:
P = PasovnaMatrika(Dict([(0,[1.0, 5.0, 9.0]), (-1,[4.0, 9.2]), (1, [2.0, 6.0]), (-2, [7.0])]), 3)
L, U = lu(P)

ErrorException: Ni diagonalno dominanbsata

In [304]:
U

3×3 PasovnaMatrika{Float64}:
 1.0   2.0   0
 0.0  -3.0   6.0
 0.0   0.0  -2.04

In [305]:
L*U


3×3 Matrix{Float64}:
 1.0  2.0   0.0
 4.0  5.0   6.0
 7.0  8.48  9.0

In [243]:
P = PasovnaMatrika(Dict([(0,[1.0, 2.5, 3.0]), (-1,[4.0, 5.0]), (1, [6.0, 7.0]), (2, [8.0])]), 3)
v = [3.0, 2, 1]

P

3×3 PasovnaMatrika{Float64}:
 1.0  6.0  8.0
 4.0  2.5  7.0
 0    5.0  3.0

In [244]:
P = PasovnaMatrika(Dict([(0,[1.0, 5.0, 9.0]), (-1,[4.0, 8.0]), (1, [2.0, 6.0]), (-2, [7.0])]), 3)
v = [1.0, 2, 3]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [245]:
A = [1 2 0; 4 5 6; 7 8 9]
lu(A)

LU{Float64, Matrix{Float64}}
L factor:
3×3 Matrix{Float64}:
 1.0       0.0  0.0
 0.142857  1.0  0.0
 0.571429  0.5  1.0
U factor:
3×3 Matrix{Float64}:
 7.0  8.0        9.0
 0.0  0.857143  -1.28571
 0.0  0.0        1.5

In [246]:
x = P\v

1.75 l, 
3 ii 1 i 1 mm 4.0
0.0 res 
3 ii 2 i 1 mm 5.0
-0.75 res 
3 ii 3 i 1 mm 6.0
-1.5 res 
--------
4.0 l, 
2 ii 1 i 1 mm 1.0
0.0 res 
2 ii 2 i 1 mm 2.0
-3.0 res 
2 ii 3 i 1 mm 0
6.0 res 
--------
0.25 l, 
3 ii 2 i 2 mm -3.0
0.0 res 
3 ii 3 i 2 mm 6.0
-3.0 res 
--------
[1.0 2.0 0; 0.0 -3.0 6.0; 0.0 0.0 -3.0]
[1.0, -2.0, 0.0]
-0.0
0.6666666666666666
1.0


3-element Vector{Float64}:
 -0.33333333333333326
  0.6666666666666666
  0.0

In [230]:
-1.5-0.25*6

-3.0

In [198]:
P * x

3-element Vector{Float64}:
  4.2
  5.6000000000000005
 21.6

In [12]:
A = [1 2; 3 4]
A

2×2 Matrix{Int64}:
 1  2
 3  4

In [13]:
A[1, 2]

2

In [11]:
zeros(0)

Float64[]

In [6]:
PasovnaMatrika

PasovnaMatrika

In [171]:
P = PasovnaMatrika(Dict([(0,[1, 2, 3]), (-1,[5,6])]), 3)

4.0 l, 
2 ii 1 i 1 mm 1.0
0.0 res 
2 ii 2 i 1 mm 2.0


3×3 PasovnaMatrika{Int64}:
 1  0  0
 5  2  0
 0  6  3

In [173]:
P[1, :]

3-element Vector{Int64}:
 1
 0
 0

In [94]:
P[1,1] = 5

5

In [95]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [100]:
P * a

[5.0, 2.0, 3.0] cc [5.0, 4.0, 9.0]
[5.0, 6.0, 0.0] cc [5.0, 12.0, 0.0]


3-element Vector{Float64}:
  5.0
  9.0
 21.0

In [101]:
P

3×3 PasovnaMatrika{Int64}:
 5  0  0
 5  2  0
 0  6  3

In [102]:
a

3-element Vector{Int64}:
 1
 2
 3