In [4]:
using LinearAlgebra

In [3]:
A = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [5]:
A[2,1]

4

In [4]:
Base.setindex!(A, 12, 3)

3×3 Matrix{Int64}:
  1  2  3
  4  5  6
 12  8  9

In [7]:
Base.size(A)

(3, 3)

In [1]:
struct PasovnaMatrika{T} <: AbstractArray{T, 2}
    pasovi::Dict{Int, Vector{T}} # 0 diagonala, 1, 2, 3...nad diagonalo, -1, -2, ... pod diagonalo
    n::Int
    # function PasovnaMatrika{T}(pasovi::Dict{Int, Vector{T}}, n::Int) where T
    #     new(pasovi, n)
    # end
end

In [2]:
function Base.size(M::PasovnaMatrika)
    return (M.n, M.n)
end

In [3]:
function Base.getindex(M::PasovnaMatrika, I::Vararg{Int, 2})
    pas = I[2] - I[1]
    if haskey(M.pasovi, pas)
        if pas >= 0
            return M.pasovi[pas][I[1]]
        else 
            return M.pasovi[pas][I[2]]
        end
    else
        return 0
    end
end

In [4]:
function Base.setindex!(M::PasovnaMatrika, v, I::Vararg{Int, 2})
    pas = I[2] - I[1]
    if haskey(M.pasovi, pas)
        if pas >= 0
            M.pasovi[pas][I[1]] = v
        else 
            M.pasovi[pas][I[2]] = v
        end
    else
        return error("Vrednosti se lahko nastavi samo v neničelnih pasovih") # dodaj cel pas naenkrat? -> setindex!(A, X, I...)
    end
end

In [29]:
import Base.*, Base.\

In [27]:
function *(M::PasovnaMatrika, v::Vector)
    y = zeros(length(v))
    for (k, pas) in M.pasovi
        curr = [zeros(min(k*-1, 0)); pas; zeros(min(k, 0))]
        y += curr .* v
        # if k > 0
        #     #add zeros to the end
        #     curr = zeros(pas)
        #     curr = vcat(pas, curr)
        #     y += curr .* v
        # elseif k < 0
        #     curr = zeros(abs(pas))
        #     curr = vcat(curr, pas)
        #     y += curr .* v
        # else
        #     y += pas .* v
        # end
    end
    return y
end

* (generic function with 365 methods)

In [ ]:
# function \(M::PasovnaMatrika, b::Vector)
#     # eliminacija  če je zg/sp trikotna ni treba tega
#     d = M.pasovi[0]
#     for (k, pas) in M.pasovi
#         if k < 0




In [11]:
zeros(0)

Float64[]

In [6]:
PasovnaMatrika

PasovnaMatrika

In [22]:
P = PasovnaMatrika(Dict([(0,[1, 2, 3])]), 3)

3×3 PasovnaMatrika{Int64}:
 1  0  0
 0  2  0
 0  0  3

In [23]:
P[1,1] = 5

5

In [25]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [28]:
P * a

3-element Vector{Float64}:
 5.0
 4.0
 9.0